<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="SL, LC, KD">
<meta name="dcterms.date" content="2023-12-18">

<title>Final data analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Analyses after revisions_files/libs/clipboard/clipboard.min.js"></script>
<script src="Analyses after revisions_files/libs/quarto-html/quarto.js"></script>
<script src="Analyses after revisions_files/libs/quarto-html/popper.min.js"></script>
<script src="Analyses after revisions_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Analyses after revisions_files/libs/quarto-html/anchor.min.js"></script>
<link href="Analyses after revisions_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Analyses after revisions_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Analyses after revisions_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Analyses after revisions_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Analyses after revisions_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Final data analysis</h1>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>SL, LC, KD </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">December 18, 2023</p>
      </div>
    </div>
    
      <div>
      <div class="quarto-title-meta-heading">Updated</div>
      <div class="quarto-title-meta-contents">
        <p class="date-modified">January 30, 2024</p>
      </div>
    </div>
      
    </div>
    
  
  </header><div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content quarto-banner-title-block" id="quarto-document-content">




<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>This is an outline of the analyses that will be carried out on the island endemics dataset.</p>
</section>
<section id="method" class="level1">
<h1>Method</h1>
<section id="constraints-to-look-out-for" class="level2">
<h2 class="anchored" data-anchor-id="constraints-to-look-out-for">Constraints to look out for</h2>
<p>Our dependent variable need to be treated carefully:</p>
<p>(1) Number of species - this is ‘count’ data (no fractions). The usual linear regression is not suited to count data. We could use a GLM (if the assumptions are met) or else a Poisson regression with a log-link function.</p>
<p>(2) Proportion of endemic species: This takes values between 0 and 1 and is therefore ‘compositional’ data. The usual linear regression cannot be used for this type of data. We’ll be using Beta regression for this.</p>
<section id="importing-data" class="level3">
<h3 class="anchored" data-anchor-id="importing-data">Importing data</h3>
</section>
<section id="number-of-species" class="level3">
<h3 class="anchored" data-anchor-id="number-of-species">Number of species</h3>
<p>Two models will be used: one of them relating the number of species on an island to “area”, “topographic complexity” and “proximity” and the other adding another variable, “population density”.</p>
<section id="poisson-and-negative-binomial-regressions-for-number-of-species---4-dependent-variables" class="level4">
<h4 class="anchored" data-anchor-id="poisson-and-negative-binomial-regressions-for-number-of-species---4-dependent-variables">Poisson and negative binomial regressions for number of species - 4 dependent variables</h4>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Poisson regression using four independent variables</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>mod3 <span class="ot">&lt;-</span> <span class="fu">glm</span>(spp <span class="sc">~</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>              area<span class="sc">+</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>              topography<span class="sc">+</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>              proximity<span class="sc">+</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>              population,</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>            <span class="at">data=</span>island_data,</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>            <span class="at">family =</span> <span class="fu">poisson</span>(<span class="at">link =</span> <span class="st">"log"</span>))</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = spp ~ area + topography + proximity + population, 
    family = poisson(link = "log"), data = island_data)

Coefficients:
              Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)  7.060e+00  3.560e-02 198.343  &lt; 2e-16 ***
area         1.401e-05  1.357e-06  10.327  &lt; 2e-16 ***
topography   1.438e-03  7.191e-05  19.994  &lt; 2e-16 ***
proximity   -4.593e-07  2.852e-07  -1.611  0.10727    
population  -7.958e-05  2.483e-05  -3.204  0.00135 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for poisson family taken to be 1)

    Null deviance: 1834.114  on 7  degrees of freedom
Residual deviance:   52.774  on 3  degrees of freedom
AIC: 137.96

Number of Fisher Scoring iterations: 3</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># test assumptions</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="co">#simulationOutput &lt;- simulateResiduals(fittedModel = mod3)</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="co">#plot(simulationOutput)</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="co"># negative binomial</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>mod3nb <span class="ot">&lt;-</span> <span class="fu">glm.nb</span>(spp <span class="sc">~</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>              area<span class="sc">+</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>              topography<span class="sc">+</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>              proximity<span class="sc">+</span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>              population,</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>            <span class="at">data=</span>island_data)</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod3nb)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm.nb(formula = spp ~ area + topography + proximity + population, 
    data = island_data, init.theta = 346.4267848, link = log)

Coefficients:
              Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)  7.077e+00  9.268e-02  76.361  &lt; 2e-16 ***
area         1.374e-05  3.777e-06   3.638 0.000275 ***
topography   1.415e-03  1.951e-04   7.253 4.06e-13 ***
proximity   -5.871e-07  7.225e-07  -0.813 0.416442    
population  -8.437e-05  5.749e-05  -1.468 0.142223    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for Negative Binomial(346.4268) family taken to be 1)

    Null deviance: 272.2978  on 7  degrees of freedom
Residual deviance:   7.9571  on 3  degrees of freedom
AIC: 110.24

Number of Fisher Scoring iterations: 1

              Theta:  346 
          Std. Err.:  205 

 2 x log-likelihood:  -98.239 </code></pre>
</div>
</div>
</section>
<section id="poisson-regression-for-number-of-species---3-dependent-variables" class="level4">
<h4 class="anchored" data-anchor-id="poisson-regression-for-number-of-species---3-dependent-variables">Poisson regression for number of species - 3 dependent variables</h4>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Poisson regression using three independent variables</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>mod4 <span class="ot">&lt;-</span> <span class="fu">glm</span>(spp <span class="sc">~</span> </span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>              area<span class="sc">+</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>              topography<span class="sc">+</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>              proximity,</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">data=</span>island_data,</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>            <span class="at">family =</span> <span class="fu">poisson</span>(<span class="at">link =</span> <span class="st">"log"</span>))</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = spp ~ area + topography + proximity, family = poisson(link = "log"), 
    data = island_data)

Coefficients:
              Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)  6.979e+00  2.527e-02 276.211   &lt;2e-16 ***
area         1.542e-05  1.293e-06  11.929   &lt;2e-16 ***
topography   1.525e-03  6.683e-05  22.827   &lt;2e-16 ***
proximity   -8.258e-08  2.620e-07  -0.315    0.753    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for poisson family taken to be 1)

    Null deviance: 1834.114  on 7  degrees of freedom
Residual deviance:   63.162  on 4  degrees of freedom
AIC: 146.35

Number of Fisher Scoring iterations: 3</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># test assumptions</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="co">#simulationOutput &lt;- simulateResiduals(fittedModel = mod4)</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="co">#plot(simulationOutput)</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="co"># negative binomial</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>mod4nb <span class="ot">&lt;-</span> <span class="fu">glm.nb</span>(spp <span class="sc">~</span> </span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>              area<span class="sc">+</span></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>              topography<span class="sc">+</span></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>              proximity,</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>            <span class="at">data=</span>island_data,</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>            )</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod4nb)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm.nb(formula = spp ~ area + topography + proximity, data = island_data, 
    init.theta = 265.6502696, link = log)

Coefficients:
              Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)  6.974e+00  6.569e-02 106.162  &lt; 2e-16 ***
area         1.586e-05  3.934e-06   4.032 5.53e-05 ***
topography   1.525e-03  2.011e-04   7.583 3.37e-14 ***
proximity   -8.313e-08  7.082e-07  -0.117    0.907    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for Negative Binomial(265.6503) family taken to be 1)

    Null deviance: 216.5013  on 7  degrees of freedom
Residual deviance:   8.0759  on 4  degrees of freedom
AIC: 110.18

Number of Fisher Scoring iterations: 1

              Theta:  266 
          Std. Err.:  153 

 2 x log-likelihood:  -100.182 </code></pre>
</div>
</div>
</section>
</section>
<section id="proportion-of-endemic-species" class="level3">
<h3 class="anchored" data-anchor-id="proportion-of-endemic-species">Proportion of endemic species</h3>
<p>Two models will be used: one of them relating the proportion of endemic species on an island to “area”, “topographic complexity” and “proximity” and the other adding another variable, “population density”.</p>
<section id="proportion-of-endemic-species---3-dependent-variables" class="level4">
<h4 class="anchored" data-anchor-id="proportion-of-endemic-species---3-dependent-variables">Proportion of endemic species - 3 dependent variables</h4>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>mod5 <span class="ot">&lt;-</span> betareg<span class="sc">::</span><span class="fu">betareg</span>(prop_endemic <span class="sc">~</span> </span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>                           area<span class="sc">+</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>                           topography<span class="sc">+</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>                           proximity,</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>                         <span class="at">data=</span>island_data)</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod5)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
betareg::betareg(formula = prop_endemic ~ area + topography + proximity, 
    data = island_data)

Standardized weighted residuals 2:
    Min      1Q  Median      3Q     Max 
-2.2333 -1.3096  0.4540  1.1390  1.3243 

Coefficients (mean model with logit link):
              Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept) -2.758e+00  4.313e-01  -6.395 1.61e-10 ***
area        -3.889e-05  2.305e-05  -1.688 0.091469 .  
topography   4.182e-03  1.228e-03   3.404 0.000664 ***
proximity   -1.173e-05  4.839e-06  -2.424 0.015359 *  

Phi coefficients (precision model with identity link):
      Estimate Std. Error z value Pr(&gt;|z|)  
(phi)    74.48      37.63   1.979   0.0478 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1 

Type of estimator: ML (maximum likelihood)
Log-likelihood:  17.6 on 5 Df
Pseudo R-squared: 0.6842
Number of iterations: 128 (BFGS) + 5 (Fisher scoring) </code></pre>
</div>
</div>
</section>
<section id="proportion-of-endemic-species---4-dependent-variables" class="level4">
<h4 class="anchored" data-anchor-id="proportion-of-endemic-species---4-dependent-variables">Proportion of endemic species - 4 dependent variables</h4>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>mod6 <span class="ot">&lt;-</span> betareg<span class="sc">::</span><span class="fu">betareg</span>(prop_endemic <span class="sc">~</span> </span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>                           area<span class="sc">+</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>                           topography<span class="sc">+</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>                           proximity<span class="sc">+</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>                           population,</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>                         <span class="at">data=</span>island_data)</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod6)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
betareg::betareg(formula = prop_endemic ~ area + topography + proximity + 
    population, data = island_data)

Standardized weighted residuals 2:
    Min      1Q  Median      3Q     Max 
-2.8213 -1.2695  0.2590  0.7880  1.7314 

Coefficients (mean model with logit link):
              Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept) -1.708e+00  3.733e-01  -4.575 4.76e-06 ***
area        -4.991e-05  1.433e-05  -3.484 0.000494 ***
topography   2.594e-03  8.469e-04   3.063 0.002194 ** 
proximity   -1.609e-05  3.141e-06  -5.121 3.03e-07 ***
population  -1.021e-03  3.386e-04  -3.016 0.002559 ** 

Phi coefficients (precision model with identity link):
      Estimate Std. Error z value Pr(&gt;|z|)  
(phi)   194.16      97.49   1.992   0.0464 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1 

Type of estimator: ML (maximum likelihood)
Log-likelihood:  21.4 on 6 Df
Pseudo R-squared: 0.8512
Number of iterations: 150 (BFGS) + 11 (Fisher scoring) </code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>mod6a <span class="ot">&lt;-</span> betareg<span class="sc">::</span><span class="fu">betareg</span>(prop_endemic <span class="sc">~</span> </span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>                           area<span class="sc">+</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>                           topography,</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>                         <span class="at">data=</span>island_data)</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod6a)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
betareg::betareg(formula = prop_endemic ~ area + topography, data = island_data)

Standardized weighted residuals 2:
    Min      1Q  Median      3Q     Max 
-2.2359 -0.7012  0.0931  0.7573  1.5862 

Coefficients (mean model with logit link):
              Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept) -3.366e+00  4.897e-01  -6.873 6.27e-12 ***
area         3.206e-06  2.480e-05   0.129   0.8971    
topography   3.001e-03  1.567e-03   1.915   0.0555 .  

Phi coefficients (precision model with identity link):
      Estimate Std. Error z value Pr(&gt;|z|)  
(phi)    39.44      20.09   1.963   0.0496 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1 

Type of estimator: ML (maximum likelihood)
Log-likelihood: 15.12 on 4 Df
Pseudo R-squared: 0.4314
Number of iterations: 73 (BFGS) + 8 (Fisher scoring) </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">AICc</span>(mod6a)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -8.908145</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>mod6b <span class="ot">&lt;-</span> betareg<span class="sc">::</span><span class="fu">betareg</span>(prop_endemic <span class="sc">~</span> </span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>                                                     topography,</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>                         <span class="at">data=</span>island_data)</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod6b)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
betareg::betareg(formula = prop_endemic ~ topography, data = island_data)

Standardized weighted residuals 2:
    Min      1Q  Median      3Q     Max 
-2.1963 -0.6052  0.0473  0.7574  1.4748 

Coefficients (mean model with logit link):
             Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept) -3.373248   0.489954  -6.885 5.79e-12 ***
topography   0.003137   0.001320   2.376   0.0175 *  

Phi coefficients (precision model with identity link):
      Estimate Std. Error z value Pr(&gt;|z|)  
(phi)    39.43      20.08   1.963   0.0496 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1 

Type of estimator: ML (maximum likelihood)
Log-likelihood: 15.11 on 3 Df
Pseudo R-squared: 0.4234
Number of iterations: 85 (BFGS) + 4 (Fisher scoring) </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">AICc</span>(mod6b)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -18.22487</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>mod6c <span class="ot">&lt;-</span> betareg<span class="sc">::</span><span class="fu">betareg</span>(prop_endemic <span class="sc">~</span> </span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>                           proximity<span class="sc">+</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>                           topography,</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>                         <span class="at">data=</span>island_data)</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod6c)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
betareg::betareg(formula = prop_endemic ~ proximity + topography, data = island_data)

Standardized weighted residuals 2:
    Min      1Q  Median      3Q     Max 
-2.0990 -1.3611  0.2668  1.0247  1.3960 

Coefficients (mean model with logit link):
              Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept) -2.926e+00  4.725e-01  -6.193 5.91e-10 ***
proximity   -7.034e-06  4.553e-06  -1.545   0.1223    
topography   2.710e-03  1.148e-03   2.360   0.0183 *  

Phi coefficients (precision model with identity link):
      Estimate Std. Error z value Pr(&gt;|z|)  
(phi)    54.52      27.62   1.974   0.0484 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1 

Type of estimator: ML (maximum likelihood)
Log-likelihood: 16.45 on 4 Df
Pseudo R-squared: 0.6609
Number of iterations: 145 (BFGS) + 10 (Fisher scoring) </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">AICc</span>(mod6c)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -11.56531</code></pre>
</div>
</div>
</section>
</section>
<section id="finding-the-best-model" class="level3">
<h3 class="anchored" data-anchor-id="finding-the-best-model">Finding the best model</h3>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Find the best fitting model</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>model.set <span class="ot">&lt;-</span> <span class="fu">list</span>(mod3, mod4)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>model.names <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"glm_all"</span>, <span class="st">"glm_area+topo+prox"</span>)</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a><span class="fu">aictab</span>(model.set, <span class="at">modnames =</span> model.names)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Model selection based on AICc:

                   K   AICc Delta_AICc AICcWt Cum.Wt     LL
glm_area+topo+prox 4 159.68       0.00   0.98   0.98 -69.17
glm_all            5 167.96       8.28   0.02   1.00 -63.98</code></pre>
</div>
</div>
</section>
</section>
</section>
<section id="summary-of-results" class="level1">
<h1>Summary of results</h1>
<section id="number-of-species-1" class="level2">
<h2 class="anchored" data-anchor-id="number-of-species-1">Number of species</h2>
<section id="including-population-density" class="level3">
<h3 class="anchored" data-anchor-id="including-population-density">Including “Population density”</h3>
<section id="glm-for-number-of-species---4-dependent-variables" class="level4">
<h4 class="anchored" data-anchor-id="glm-for-number-of-species---4-dependent-variables">GLM for number of species - 4 dependent variables</h4>
<p>topography P = 0.0278*</p>
<p>Null deviance: 3752264 on 7 degrees of freedom</p>
<p>Residual deviance: 153099 on 3 degrees of freedom</p>
</section>
<section id="poisson-regression-for-number-of-species---4-dependent-variables" class="level4">
<h4 class="anchored" data-anchor-id="poisson-regression-for-number-of-species---4-dependent-variables">Poisson regression for number of species - 4 dependent variables</h4>
<p>area P &lt; 0.0001***</p>
<p>topography P &lt; 0.0001***</p>
<p>population P = 0.001***</p>
<p>Null deviance: 1834.114 on 7 degrees of freedom</p>
<p>Residual deviance: 52.774 on 3 degrees of freedom</p>
</section>
</section>
<section id="excluding-population-density" class="level3">
<h3 class="anchored" data-anchor-id="excluding-population-density">Excluding “Population density”</h3>
<section id="glm-for-number-of-species---3-dependent-variables" class="level4">
<h4 class="anchored" data-anchor-id="glm-for-number-of-species---3-dependent-variables">GLM for number of species - 3 dependent variables</h4>
<p>area P = 0.05*</p>
<p>topography P = 0.009***</p>
<p>Null deviance: 3752264 on 7 degrees of freedom</p>
<p>Residual deviance: 159209 on 4 degrees of freedom</p>
</section>
<section id="poisson-regression-for-number-of-species---3-dependent-variables-1" class="level4">
<h4 class="anchored" data-anchor-id="poisson-regression-for-number-of-species---3-dependent-variables-1">Poisson regression for number of species - 3 dependent variables</h4>
<p>area P &lt; 0.0001***</p>
<p>topography P &lt; 0.0001***</p>
<p>Null deviance: 1834.114 on 7 degrees of freedom</p>
<p>Residual deviance: 63.162 on 4 degrees of freedom</p>
</section>
</section>
</section>
<section id="proportion-of-endemic-species-1" class="level2">
<h2 class="anchored" data-anchor-id="proportion-of-endemic-species-1">Proportion of endemic species</h2>
<section id="including-population-density-1" class="level3">
<h3 class="anchored" data-anchor-id="including-population-density-1">Including “Population density”</h3>
<section id="proportion-of-endemic-species---4-dependent-variables-1" class="level4">
<h4 class="anchored" data-anchor-id="proportion-of-endemic-species---4-dependent-variables-1">Proportion of endemic species - 4 dependent variables</h4>
<p>area P &lt; 0.0001***</p>
<p>topography P = 0.002**</p>
<p>proximity P &lt; 0.0001***</p>
<p>population P = 0.003**</p>
</section>
</section>
<section id="excluding-population-density-1" class="level3">
<h3 class="anchored" data-anchor-id="excluding-population-density-1">Excluding “Population density”</h3>
<section id="proportion-of-endemic-species---3-dependent-variables-1" class="level4">
<h4 class="anchored" data-anchor-id="proportion-of-endemic-species---3-dependent-variables-1">Proportion of endemic species - 3 dependent variables</h4>
<p>topography P &lt; 0.0001***</p>
<p>proximity P = 0.015*</p>
</section>
</section>
</section>
</section>
<section id="removal-of-outliers-using-only-large-islands" class="level1">
<h1>Removal of outliers (using only large islands)</h1>
<p>The analysis will now be carried out again using only the five large islands and excluding the archipelagos.</p>
<section id="number-of-species-2" class="level3">
<h3 class="anchored" data-anchor-id="number-of-species-2">Number of species</h3>
<p>Two models will be used: one of them relating the number of species on an island to “area”, “topographic complexity” and “proximity” and the other adding another variable, “population density”.</p>
<section id="glm-for-number-of-species---4-dependent-variables-1" class="level4">
<h4 class="anchored" data-anchor-id="glm-for-number-of-species---4-dependent-variables-1">GLM for number of species - 4 dependent variables</h4>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># GLM using four independent variables</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>mod1 <span class="ot">&lt;-</span> <span class="fu">glm</span>(spp <span class="sc">~</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>              area<span class="sc">+</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>              topography<span class="sc">+</span></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>              proximity<span class="sc">+</span></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>              population,</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>            <span class="at">data=</span>island_data)</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = spp ~ area + topography + proximity + population, 
    data = island_data)

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)
(Intercept)  2.530e+02        NaN     NaN      NaN
area         4.956e-02        NaN     NaN      NaN
topography   4.296e+00        NaN     NaN      NaN
proximity   -6.466e-05        NaN     NaN      NaN
population  -1.993e+00        NaN     NaN      NaN

(Dispersion parameter for gaussian family taken to be NaN)

    Null deviance: 1.3935e+06  on 4  degrees of freedom
Residual deviance: 1.0340e-24  on 0  degrees of freedom
AIC: -258

Number of Fisher Scoring iterations: 1</code></pre>
</div>
</div>
</section>
<section id="glm-for-number-of-species---3-dependent-variables-1" class="level4">
<h4 class="anchored" data-anchor-id="glm-for-number-of-species---3-dependent-variables-1">GLM for number of species - 3 dependent variables</h4>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># GLM using three independent variables</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>mod2 <span class="ot">&lt;-</span> <span class="fu">glm</span>(spp <span class="sc">~</span> </span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>              area<span class="sc">+</span></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>              topography<span class="sc">+</span></span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>              proximity,</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">data=</span>island_data)</span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = spp ~ area + topography + proximity, data = island_data)

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)
(Intercept) 2.296e+02  4.764e+02   0.482    0.714
area        4.283e-02  1.506e-02   2.844    0.215
topography  4.117e+00  9.338e-01   4.408    0.142
proximity   4.544e-05  3.660e-03   0.012    0.992

(Dispersion parameter for gaussian family taken to be 40488.27)

    Null deviance: 1393487  on 4  degrees of freedom
Residual deviance:   40488  on 1  degrees of freedom
AIC: 69.186

Number of Fisher Scoring iterations: 2</code></pre>
</div>
</div>
</section>
<section id="poisson-regression-for-number-of-species---4-dependent-variables-1" class="level4">
<h4 class="anchored" data-anchor-id="poisson-regression-for-number-of-species---4-dependent-variables-1">Poisson regression for number of species - 4 dependent variables</h4>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Poisson regression using four independent variables</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>mod3 <span class="ot">&lt;-</span> <span class="fu">glm</span>(spp <span class="sc">~</span></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>              area<span class="sc">+</span></span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>              topography<span class="sc">+</span></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>              proximity<span class="sc">+</span></span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>              population,</span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>            <span class="at">data=</span>island_data,</span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a>            <span class="at">family =</span> <span class="fu">poisson</span>(<span class="at">link =</span> <span class="st">"log"</span>))</span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = spp ~ area + topography + proximity + population, 
    family = poisson(link = "log"), data = island_data)

Coefficients:
              Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)  6.903e+00  4.830e-02 142.900  &lt; 2e-16 ***
area         2.097e-05  1.714e-06  12.235  &lt; 2e-16 ***
topography   1.857e-03  1.014e-04  18.309  &lt; 2e-16 ***
proximity   -4.902e-07  3.901e-07  -1.257    0.209    
population  -1.366e-03  2.084e-04  -6.557 5.49e-11 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for poisson family taken to be 1)

    Null deviance:  5.7856e+02  on 4  degrees of freedom
Residual deviance: -6.7946e-14  on 0  degrees of freedom
AIC: 58.08

Number of Fisher Scoring iterations: 2</code></pre>
</div>
</div>
</section>
<section id="poisson-regression-for-number-of-species---3-dependent-variables-2" class="level4">
<h4 class="anchored" data-anchor-id="poisson-regression-for-number-of-species---3-dependent-variables-2">Poisson regression for number of species - 3 dependent variables</h4>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Poisson regression using three independent variables</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>mod4 <span class="ot">&lt;-</span> <span class="fu">glm</span>(spp <span class="sc">~</span> </span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>              area<span class="sc">+</span></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>              topography<span class="sc">+</span></span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>              proximity,</span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">data=</span>island_data,</span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>            <span class="at">family =</span> <span class="fu">poisson</span>(<span class="at">link =</span> <span class="st">"log"</span>))</span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = spp ~ area + topography + proximity, family = poisson(link = "log"), 
    data = island_data)

Coefficients:
              Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)  6.925e+00  4.796e-02 144.403   &lt;2e-16 ***
area         1.576e-05  1.526e-06  10.327   &lt;2e-16 ***
topography   1.641e-03  9.499e-05  17.274   &lt;2e-16 ***
proximity   -1.842e-07  3.863e-07  -0.477    0.633    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for poisson family taken to be 1)

    Null deviance: 578.558  on 4  degrees of freedom
Residual deviance:  43.292  on 1  degrees of freedom
AIC: 99.371

Number of Fisher Scoring iterations: 3</code></pre>
</div>
</div>
</section>
</section>
<section id="proportion-of-endemic-species-2" class="level3">
<h3 class="anchored" data-anchor-id="proportion-of-endemic-species-2">Proportion of endemic species</h3>
<p>Two models will be used: one of them relating the proportion of endemic species on an island to “area”, “topographic complexity” and “proximity” and the other adding another variable, “population density”.</p>
<section id="proportion-of-endemic-species---3-dependent-variables-2" class="level4">
<h4 class="anchored" data-anchor-id="proportion-of-endemic-species---3-dependent-variables-2">Proportion of endemic species - 3 dependent variables</h4>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>mod5 <span class="ot">&lt;-</span> betareg<span class="sc">::</span><span class="fu">betareg</span>(prop_endemic <span class="sc">~</span> </span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>                           area<span class="sc">+</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>                           topography<span class="sc">+</span></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>                           proximity,</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>                         <span class="at">data=</span>island_data)</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod5)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
betareg::betareg(formula = prop_endemic ~ area + topography + proximity, 
    data = island_data)

Standardized weighted residuals 2:
   Min     1Q Median     3Q    Max 
-2.236 -2.236 -2.236  2.236  2.236 

Coefficients (mean model with logit link):
              Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept) -1.470e+00  4.262e-02  -34.49   &lt;2e-16 ***
area        -5.180e-05  1.257e-06  -41.22   &lt;2e-16 ***
topography   1.318e-03  9.164e-05   14.38   &lt;2e-16 ***
proximity   -9.718e-06  2.968e-07  -32.75   &lt;2e-16 ***

Phi coefficients (precision model with identity link):
      Estimate Std. Error z value Pr(&gt;|z|)
(phi)    30987      19598   1.581    0.114
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1 

Type of estimator: ML (maximum likelihood)
Log-likelihood: 24.68 on 5 Df
Pseudo R-squared: 0.9964
Number of iterations: 504 (BFGS) + 9 (Fisher scoring) </code></pre>
</div>
</div>
</section>
<section id="proportion-of-endemic-species---4-dependent-variables-2" class="level4">
<h4 class="anchored" data-anchor-id="proportion-of-endemic-species---4-dependent-variables-2">Proportion of endemic species - 4 dependent variables</h4>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co">#mod6 &lt;- betareg::betareg(prop_endemic ~ </span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>                          <span class="co"># area+</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>                          <span class="co"># topography+</span></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>                          <span class="co"># proximity+</span></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>                          <span class="co"># population,</span></span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>                        <span class="co"># data=island_data)</span></span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a><span class="co">#summary(mod6)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
</section>
<section id="new-results" class="level2">
<h2 class="anchored" data-anchor-id="new-results">New results</h2>
</section>
<section id="number-of-species-3" class="level2">
<h2 class="anchored" data-anchor-id="number-of-species-3">Number of species</h2>
<section id="including-population-density-2" class="level3">
<h3 class="anchored" data-anchor-id="including-population-density-2">Including “Population density”</h3>
<section id="glm-for-number-of-species---4-dependent-variables-2" class="level4">
<h4 class="anchored" data-anchor-id="glm-for-number-of-species---4-dependent-variables-2">GLM for number of species - 4 dependent variables</h4>
<p>Not worked out; errors noted.</p>
</section>
<section id="poisson-regression-for-number-of-species---4-dependent-variables-2" class="level4">
<h4 class="anchored" data-anchor-id="poisson-regression-for-number-of-species---4-dependent-variables-2">Poisson regression for number of species - 4 dependent variables</h4>
<p>area P &lt; 0.0001***</p>
<p>topography P &lt; 0.0001***</p>
<p>population P &lt; 0.001***</p>
<p>Null deviance: 5.7856e+02 on 4 degrees of freedom</p>
<p>Residual deviance: -6.7946e-14 on 0 degrees of freedom</p>
</section>
</section>
<section id="excluding-population-density-2" class="level3">
<h3 class="anchored" data-anchor-id="excluding-population-density-2">Excluding “Population density”</h3>
<section id="glm-for-number-of-species---3-dependent-variables-2" class="level4">
<h4 class="anchored" data-anchor-id="glm-for-number-of-species---3-dependent-variables-2">GLM for number of species - 3 dependent variables</h4>
<p>Null deviance: 1393487 on 4 degrees of freedom</p>
<p>Residual deviance: 40488 on 1 degrees of freedom</p>
</section>
<section id="poisson-regression-for-number-of-species---3-dependent-variables-3" class="level4">
<h4 class="anchored" data-anchor-id="poisson-regression-for-number-of-species---3-dependent-variables-3">Poisson regression for number of species - 3 dependent variables</h4>
<p>area P &lt; 0.0001***</p>
<p>topography P &lt; 0.0001***</p>
<p>Null deviance: 578.558 on 4 degrees of freedom</p>
<p>Residual deviance: 43.292 on 1 degrees of freedom</p>
</section>
</section>
</section>
<section id="proportion-of-endemic-species-3" class="level2">
<h2 class="anchored" data-anchor-id="proportion-of-endemic-species-3">Proportion of endemic species</h2>
<section id="including-population-density-3" class="level3">
<h3 class="anchored" data-anchor-id="including-population-density-3">Including “Population density”</h3>
<section id="proportion-of-endemic-species---4-dependent-variables-3" class="level4">
<h4 class="anchored" data-anchor-id="proportion-of-endemic-species---4-dependent-variables-3">Proportion of endemic species - 4 dependent variables</h4>
<p>Not worked out - errors recorded</p>
</section>
</section>
<section id="excluding-population-density-3" class="level3">
<h3 class="anchored" data-anchor-id="excluding-population-density-3">Excluding “Population density”</h3>
<section id="proportion-of-endemic-species---3-dependent-variables-3" class="level4">
<h4 class="anchored" data-anchor-id="proportion-of-endemic-species---3-dependent-variables-3">Proportion of endemic species - 3 dependent variables</h4>
<p>area P &lt; 0.0001***</p>
<p>topography P &lt; 0.0001***</p>
<p>proximity P &lt; 0.0001***</p>
</section>
</section>
</section>
</section>
<section id="conclusions" class="level1">
<h1>Conclusions</h1>
<table class="table">
<caption>Comparison of models</caption>
<colgroup>
<col style="width: 36%">
<col style="width: 11%">
<col style="width: 17%">
<col style="width: 16%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th>Model</th>
<th>Area</th>
<th>Topography</th>
<th>Proximity</th>
<th>Population</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>All islands 4dv GLM</td>
<td></td>
<td>*</td>
<td>ns</td>
<td>ns</td>
</tr>
<tr class="even">
<td>All islands 4dv Poisson</td>
<td>***</td>
<td>***</td>
<td>ns</td>
<td>***</td>
</tr>
<tr class="odd">
<td>All islands 4dv beta</td>
<td>***</td>
<td>**</td>
<td>***</td>
<td>**</td>
</tr>
<tr class="even">
<td>All islands 3dv GLM</td>
<td>*</td>
<td>***</td>
<td>ns</td>
<td>not tested</td>
</tr>
<tr class="odd">
<td>All islands 3dv Poisson</td>
<td>***</td>
<td>***</td>
<td>ns</td>
<td>not tested</td>
</tr>
<tr class="even">
<td>All islands 3dv beta</td>
<td>ns</td>
<td>***</td>
<td>*</td>
<td>not tested</td>
</tr>
<tr class="odd">
<td>5 islands 4dv GLM</td>
<td>NA</td>
<td>NA</td>
<td>NA</td>
<td>NA</td>
</tr>
<tr class="even">
<td>5 islands 4dv Poisson</td>
<td>***</td>
<td>***</td>
<td>ns</td>
<td>***</td>
</tr>
<tr class="odd">
<td>5 islands 4dv beta</td>
<td>NA</td>
<td>NA</td>
<td>NA</td>
<td>NA</td>
</tr>
<tr class="even">
<td>5 islands 3dv GLM</td>
<td>ns</td>
<td>ns</td>
<td>ns</td>
<td>not tested</td>
</tr>
<tr class="odd">
<td>5 islands 3dv Poisson</td>
<td>***</td>
<td>***</td>
<td>ns</td>
<td>not tested</td>
</tr>
<tr class="even">
<td>5 islands 3dv beta</td>
<td>***</td>
<td>***</td>
<td>***</td>
<td>not tested</td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>endemism3 <span class="ot">&lt;-</span> island_data <span class="sc">|&gt;</span> dplyr<span class="sc">::</span><span class="fu">select</span>(spp,topography,area,proximity,population)</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a><span class="co">#Load the required packages</span></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(leaps)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'leaps' was built under R version 4.3.1</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the data</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="co">#data(endemism3)</span></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute best subsets regression</span></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>models <span class="ot">&lt;-</span> <span class="fu">regsubsets</span>(spp <span class="sc">~</span> ., <span class="at">data =</span> endemism3, <span class="at">nvmax =</span> <span class="dv">4</span>)</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the summary of the models</span></span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(models)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Subset selection object
Call: regsubsets.formula(spp ~ ., data = endemism3, nvmax = 4)
4 Variables  (and intercept)
           Forced in Forced out
topography     FALSE      FALSE
area           FALSE      FALSE
proximity      FALSE      FALSE
population     FALSE      FALSE
1 subsets of each size up to 4
Selection Algorithm: exhaustive
         topography area proximity population
1  ( 1 ) "*"        " "  " "       " "       
2  ( 1 ) "*"        "*"  " "       " "       
3  ( 1 ) "*"        "*"  " "       "*"       
4  ( 1 ) "*"        "*"  "*"       "*"       </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(models, <span class="at">scale =</span> <span class="st">"adjr2"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Analyses-after-revisions_files/figure-html/best.subsets-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>?</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>